services:
# nginx
#  web:
 #   image: nginx:latest
  #  ports:
   #   - "80:80"
    #volumes:
     # - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - bridge-net
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json.ts:/app/tsconfig.json.ts
  svm_service:
    build:
        dockerfile: ./SVM_service/Dockerfile
    ports:
      - "5001:8000"
    volumes:
      - ./SVM_service/test.py:/app/test.py
      - ./SVM_service/app.py:/app/app.py
      - ./SVM_service/requirements.txt:/app/requirements.txt
      - ./models/svm_model.pkl:/app/model.pkl
      - ./models/scaler.pkl:/app/scl.pkl

  vgg19_service:
     build:
       dockerfile: ./VGG19_service/Dockerfile
     volumes:
        - ./dataset/metal.wav:/app/metal.wav
        - ./VGG19_service/test.py:/app/test.py
        - "./VGG19_service/app.py:/app/app.py"
        - "./VGG19_service/requirements.txt:/app/requirements.txt"
        - "./models/VGG19.keras:/app/model.keras"
        - "./models/VGG19.h5:/app/model.h5"
        #- ./VGG19_service/temp_spectrogram.png:/app/temp_spectrogram.png
     environment:
        - KAGGLE_JSON=${{ secrets.KAGGLE_JSON }}
     ports:
        - "5002:8000"
