services:
# nginx
#  web:
 #   image: nginx:latest
  #  ports:
   #   - "80:80"
    #volumes:
     # - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - bridge-net
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/tsconfig.json.ts:/app/tsconfig.json.ts
  svm_service:
    build:
        dockerfile: ./SVM_service/Dockerfile
    ports:
      - "5001:8000"
    volumes:
      - ./SVM_service/app.py:/app/app.py
      - ./SVM_service/requirements.txt:/app/requirements.txt
      - ./models/svm_model.pkl:/app/model.pkl
      - ./models/scaler.pkl:/app/scl.pkl

  vgg19_service:
     build:
       dockerfile: ./VGG19_service/Dockerfile
     volumes:
        - "./VGG19_service/app.py:/app/app.py"
        - "./VGG19_service/requirements.txt:/app/requirements.txt"
        - "./models/VGG19.keras:/app/model.keras"
     ports:
        - "5002:8000"
