name: Build and Deploy Docker Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "${{ secrets.KAGGLE_JSON }}"
